language: bash

# for secret experimental features ;)
sudo: 9000

env:
  - VARIANT=apache
  - VARIANT=fpm

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VARIANT"
  - image="wordpress:$VARIANT"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
